name: All Pull Request Build and Deploy

on: [pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: npm run adapt
      - name: Deploy to https://${{GITHUB_REPOSITORY#*/}}-PR-${{GITHUB_REF##*/}}.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "https://${{GITHUB_REPOSITORY#*/}}-PR-${{GITHUB_REF##*/}}.surge.sh"
          project: "build"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
